version: '3'
services:

  game-vite:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ngame-vite
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "${HTTP_PORT}:8088" #Change this port in vite.config.js
    volumes:
      - ".:/var/www"
      - "./node_modules:/var/www/node_modules"
    networks:
      - game-vite-network

networks:
  game-vite-network:
    driver: bridge
